apiVersion: v1
kind: Service
metadata:
  name: blog-app-service
spec:
  type: NodePort
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007 # Port accessible depuis votre machine